//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.ConfTpl {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataLabResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataLabResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.ConfTpl.DataLabResource", typeof(DataLabResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alias.
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application Settings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application settings will allow DataLab to be customized when installed on Azure.
        ///        You will need to provide the following.
        /// </summary>
        public static string ApplicationSettingsWillAllowDataLab {
            get {
                return ResourceManager.GetString("ApplicationSettingsWillAllowDataLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blob Storage Info.
        /// </summary>
        public static string BlobStorageInfo {
            get {
                return ResourceManager.GetString("BlobStorageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data Catalog definition.
        /// </summary>
        public static string CatalogDefinition {
            get {
                return ResourceManager.GetString("CatalogDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This section allows you to configure the data catalog that OGDI DataLab will use. Leave this section blank if you want to use an extern data service..
        /// </summary>
        public static string CatalogDefinitionDescription {
            get {
                return ResourceManager.GetString("CatalogDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to see how.
        /// </summary>
        public static string ClickToSeeHow {
            get {
                return ResourceManager.GetString("ClickToSeeHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data Service DNS.
        /// </summary>
        public static string DataServiceDNS {
            get {
                return ResourceManager.GetString("DataServiceDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disclaimer.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Once complete you will need to provide the following:.
        /// </summary>
        public static string OnceComplete {
            get {
                return ResourceManager.GetString("OnceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Primary Access Key.
        /// </summary>
        public static string PrimaryAccessKey {
            get {
                return ResourceManager.GetString("PrimaryAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recaptcha Private Key.
        /// </summary>
        public static string RecaptchaPrivateKey {
            get {
                return ResourceManager.GetString("RecaptchaPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recaptcha Public Key.
        /// </summary>
        public static string RecaptchaPublickey {
            get {
                return ResourceManager.GetString("RecaptchaPublickey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Storage Account Name.
        /// </summary>
        public static string StorageAccountName {
            get {
                return ResourceManager.GetString("StorageAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The use of Blob Storage is required for this package. If you already have an existing
        ///        Storage Account.
        ///    If you need to create a storage account for blob storage, click &lt;a href=&quot;#&quot; data-toggle=&quot;modal&quot;
        ///        data-target=&quot;#createTableStorage&quot;&gt;here&lt;/a&gt; for details on how to create one..
        /// </summary>
        public static string TheUseOfBlobStorageIsRequired {
            get {
                return ResourceManager.GetString("TheUseOfBlobStorageIsRequired", resourceCulture);
            }
        }
    }
}
