//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.ConfTpl {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OpenIntelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenIntelResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.ConfTpl.OpenIntelResource", typeof(OpenIntelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application Settings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application settings will allow DataLab to be customized when installed on Azure.
        ///        You will need to provide the following.
        /// </summary>
        public static string ApplicationSettingsWillAllowDataLab {
            get {
                return ResourceManager.GetString("ApplicationSettingsWillAllowDataLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bing Service Key.
        /// </summary>
        public static string BingServiceKey {
            get {
                return ResourceManager.GetString("BingServiceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blob Storage Info.
        /// </summary>
        public static string BlobStorageInfo {
            get {
                return ResourceManager.GetString("BlobStorageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to see how.
        /// </summary>
        public static string ClickToSeeHow {
            get {
                return ResourceManager.GetString("ClickToSeeHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database Hostname.
        /// </summary>
        public static string DatabaseHostname {
            get {
                return ResourceManager.GetString("DatabaseHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database Name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à database-name.
        /// </summary>
        public static string DatabaseNamePlaceholder {
            get {
                return ResourceManager.GetString("DatabaseNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you do not have a SQL Azure database already created, click &lt;a href=&apos;#&apos; data-toggle=&apos;modal&apos;
        ///            data-target=&apos;#CreateSqlAzureDb&apos; rel=&apos;tooltip&apos; data-original-title=&apos;Click to see how&apos;&gt;
        ///            here&lt;/a&gt; for instructions to create a SQL Azure database..
        /// </summary>
        public static string IfYouDoNotHaveASqlAzure {
            get {
                return ResourceManager.GetString("IfYouDoNotHaveASqlAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à key provided by Bing API.
        /// </summary>
        public static string KeyProvidedByBingAPI {
            get {
                return ResourceManager.GetString("KeyProvidedByBingAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Once complete you will need to provide the following:.
        /// </summary>
        public static string OnceComplete {
            get {
                return ResourceManager.GetString("OnceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Once the database is created, enter the values below..
        /// </summary>
        public static string OnceTheDataBaseIsCreated {
            get {
                return ResourceManager.GetString("OnceTheDataBaseIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à password you created.
        /// </summary>
        public static string PasswordYouCreated {
            get {
                return ResourceManager.GetString("PasswordYouCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Primary Access Key.
        /// </summary>
        public static string PrimaryAccessKey {
            get {
                return ResourceManager.GetString("PrimaryAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQL Azure Info.
        /// </summary>
        public static string SQLAzureInfo {
            get {
                return ResourceManager.GetString("SQLAzureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Storage Account Name.
        /// </summary>
        public static string StorageAccountName {
            get {
                return ResourceManager.GetString("StorageAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The use of Blob Storage is required for this package. If you already have an existing
        ///        Storage Account.
        ///    If you need to create a storage account for blob storage, click &lt;a href=&quot;#&quot; data-toggle=&quot;modal&quot;
        ///        data-target=&quot;#createTableStorage&quot;&gt;here&lt;/a&gt; for details on how to create one..
        /// </summary>
        public static string TheUseOfBlobStorageIsRequired {
            get {
                return ResourceManager.GetString("TheUseOfBlobStorageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à username@yourserver.
        /// </summary>
        public static string UsernameAtYourServer {
            get {
                return ResourceManager.GetString("UsernameAtYourServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yourserver.database.windows.com.
        /// </summary>
        public static string YourServerDatabase {
            get {
                return ResourceManager.GetString("YourServerDatabase", resourceCulture);
            }
        }
    }
}
