//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.ConfTpl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OpenTurfResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenTurfResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.ConfTpl.OpenTurfResource", typeof(OpenTurfResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Active Directory Information.
        /// </summary>
        public static string ADInfo {
            get {
                return ResourceManager.GetString("ADInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a login username to use for bit.ly URL shortening.
        /// </summary>
        public static string ALoginUsernameToUse {
            get {
                return ResourceManager.GetString("ALoginUsernameToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an API key to use for URL Shortening.
        /// </summary>
        public static string AnAPIKeyToUse {
            get {
                return ResourceManager.GetString("AnAPIKeyToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings will allow ODAF OpenTurf to be customized when installed on Azure.
        ///        You will need to provide the following.
        /// </summary>
        public static string ApplicationSettingsWillAllow {
            get {
                return ResourceManager.GetString("ApplicationSettingsWillAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Url.
        /// </summary>
        public static string AppUrl {
            get {
                return ResourceManager.GetString("AppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit.ly API Key.
        /// </summary>
        public static string BitlyAPIKey {
            get {
                return ResourceManager.GetString("BitlyAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit.ly Login.
        /// </summary>
        public static string BitlyLogin {
            get {
                return ResourceManager.GetString("BitlyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback Url.
        /// </summary>
        public static string CallbackUrl {
            get {
                return ResourceManager.GetString("CallbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see how.
        /// </summary>
        public static string ClickToSeeHow {
            get {
                return ResourceManager.GetString("ClickToSeeHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Key.
        /// </summary>
        public static string ConsumerKey {
            get {
                return ResourceManager.GetString("ConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consumer key provided by Twitter.
        /// </summary>
        public static string ConsumerKeyProvidedByTwitter {
            get {
                return ResourceManager.GetString("ConsumerKeyProvidedByTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Secret.
        /// </summary>
        public static string ConsumerSecret {
            get {
                return ResourceManager.GetString("ConsumerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consumer secret provided by Twitter.
        /// </summary>
        public static string ConsumerSecretProvidedByTwitter {
            get {
                return ResourceManager.GetString("ConsumerSecretProvidedByTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Hostname.
        /// </summary>
        public static string DatabaseHostname {
            get {
                return ResourceManager.GetString("DatabaseHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not have a SQL Azure database already created, click &lt;a href=&apos;#&apos; data-toggle=&apos;modal&apos;
        ///            data-target=&apos;#CreateSqlAzureDb&apos; rel=&apos;tooltip&apos; data-original-title=&apos;Click to see how&apos;&gt;
        ///            here&lt;/a&gt; for instructions to create a SQL Azure database.&lt;/p&gt;.
        /// </summary>
        public static string IfYouDoNotHaveAlready {
            get {
                return ResourceManager.GetString("IfYouDoNotHaveAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Cloud Service in Microsoft Azure.
        /// </summary>
        public static string NameOfTheApplication {
            get {
                return ResourceManager.GetString("NameOfTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the database is created, enter the values below..
        /// </summary>
        public static string OnceDatabaseIsCreated {
            get {
                return ResourceManager.GetString("OnceDatabaseIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODAF OpenTurf has Twitter integration and will require some details to be functional.
        ///        Please refer to Twitter Developer documentation at &lt;a href=&quot;https://dev.twitter.com&quot;&gt;
        ///            https://dev.twitter.com&lt;/a&gt; on how to setup appropriate twitter keys. You will
        ///        need to provide the following.
        /// </summary>
        public static string OpenTurfHasTwitterIntegration {
            get {
                return ResourceManager.GetString("OpenTurfHasTwitterIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password you created.
        /// </summary>
        public static string PasswordYouCreated {
            get {
                return ResourceManager.GetString("PasswordYouCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same callback URL setup when creating app on Twitter.
        /// </summary>
        public static string SameCallBackURLSetup {
            get {
                return ResourceManager.GetString("SameCallBackURLSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Azure Info.
        /// </summary>
        public static string SQLAzureInfo {
            get {
                return ResourceManager.GetString("SQLAzureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Settings.
        /// </summary>
        public static string TwitterSettings {
            get {
                return ResourceManager.GetString("TwitterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Username to be used as Admin.
        /// </summary>
        public static string TwitterUsernameToUse {
            get {
                return ResourceManager.GetString("TwitterUsernameToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username that will be used for administration.
        /// </summary>
        public static string UsernameThatWillBeUsed {
            get {
                return ResourceManager.GetString("UsernameThatWillBeUsed", resourceCulture);
            }
        }
    }
}
