//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateSqlAzureDbResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateSqlAzureDbResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.Help.CreateSqlAzureDbResource", typeof(CreateSqlAzureDbResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;b&gt;OK&lt;/b&gt;. At this point the database and server will be created in a few minutes..
        /// </summary>
        public static string ClickFinish {
            get {
                return ResourceManager.GetString("ClickFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;b&gt;SQL DATABASES&lt;/b&gt;..
        /// </summary>
        public static string ClickOnDatabase {
            get {
                return ResourceManager.GetString("ClickOnDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;b&gt;CREATE A SQL DATABASE&lt;/b&gt;..
        /// </summary>
        public static string ClickTheCreateANewDatabase {
            get {
                return ResourceManager.GetString("ClickTheCreateANewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an administrator login and password. Select a region and do not forget to check the box &lt;b&gt;ALLOW WINDOWS AZURE SERVICES TO ACCESS THE SERVER&lt;/b&gt;..
        /// </summary>
        public static string CreateAnAdministratorLogin {
            get {
                return ResourceManager.GetString("CreateAnAdministratorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to &lt;a href=&quot;https://manage.windowsazure.com&quot; target=&quot;_blank&quot;&gt;https://manage.windowsazure.com&lt;/a&gt; and sign in..
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to create a SQL Azure Database.
        /// </summary>
        public static string HowToGetCreateSqlAzureDatabase {
            get {
                return ResourceManager.GetString("HowToGetCreateSqlAzureDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the &lt;b&gt;NEW SQL DATABASE&lt;/b&gt; dialog, choose a name for your database. You can then select an existing database server or create a new one..
        /// </summary>
        public static string InTheCreateDatabaseDialog {
            get {
                return ResourceManager.GetString("InTheCreateDatabaseDialog", resourceCulture);
            }
        }
    }
}
