//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18051
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateCloudServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateCloudServiceResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.Help.CreateCloudServiceResource", typeof(CreateCloudServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on &lt;b&gt;CREATE CLOUD SERVICE&lt;/b&gt;. After a few seconds, your &lt;b&gt;Cloud Service&lt;/b&gt; is operational..
        /// </summary>
        public static string ClickOkAndAfter {
            get {
                return ResourceManager.GetString("ClickOkAndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on &lt;b&gt;CLOUD SERVICES&lt;/b&gt;..
        /// </summary>
        public static string ClickOnCloudServices {
            get {
                return ResourceManager.GetString("ClickOnCloudServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on &lt;b&gt;NEW&lt;/b&gt;..
        /// </summary>
        public static string ClickOnNewCloudService {
            get {
                return ResourceManager.GetString("ClickOnNewCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For the Open Data Platform Installer to function properly, an &lt;b&gt;empty Cloud Service&lt;/b&gt; is required under your Windows Azure subscription to install selected products..
        /// </summary>
        public static string ForOpenDataPlatformInstallerToFunction {
            get {
                return ResourceManager.GetString("ForOpenDataPlatformInstallerToFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to &lt;a href=&quot;https://manage.windowsazure.com&quot; target=&quot;_blank&quot;&gt;https://manage.windowsazure.com&lt;/a&gt; and sign in..
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How To Create A Windows Azure Cloud Service.
        /// </summary>
        public static string HowToCreateAWindowsAzureCloudService {
            get {
                return ResourceManager.GetString("HowToCreateAWindowsAzureCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image001.jpg.
        /// </summary>
        public static string Image1 {
            get {
                return ResourceManager.GetString("Image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image002.jpg.
        /// </summary>
        public static string Image2 {
            get {
                return ResourceManager.GetString("Image2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image003.jpg.
        /// </summary>
        public static string Image3 {
            get {
                return ResourceManager.GetString("Image3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image004.jpg.
        /// </summary>
        public static string Image4 {
            get {
                return ResourceManager.GetString("Image4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In the panel that appears, choose &lt;b&gt;QUICK CREATE&lt;/b&gt;. Then enter your URL and select a region..
        /// </summary>
        public static string InTheCreateANewCloudService {
            get {
                return ResourceManager.GetString("InTheCreateANewCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following steps allow you to create a &lt;b&gt;Cloud Service&lt;/b&gt; under your Windows Azure subscription. Go ahead and create a hosted service for every product you wish to install..
        /// </summary>
        public static string TheFollowingStepsAllowYou {
            get {
                return ResourceManager.GetString("TheFollowingStepsAllowYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must create one &lt;b&gt;Cloud Service&lt;/b&gt; for every product you install and cannot deploy multiple products to one Cloud Service. In the deployment step of the installer, you will have to select which &lt;b&gt;Cloud Service&lt;/b&gt; the product should be assigned to..
        /// </summary>
        public static string YouMustCreateOneCloudService {
            get {
                return ResourceManager.GetString("YouMustCreateOneCloudService", resourceCulture);
            }
        }
    }
}
