//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateCloudServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateCloudServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.Help.CreateCloudServiceResource", typeof(CreateCloudServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;b&gt;CREATE CLOUD SERVICE&lt;/b&gt;. After a few seconds, your &lt;b&gt;Cloud Service&lt;/b&gt; is operational..
        /// </summary>
        public static string ClickOkAndAfter {
            get {
                return ResourceManager.GetString("ClickOkAndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;b&gt;CLOUD SERVICES&lt;/b&gt;..
        /// </summary>
        public static string ClickOnCloudServices {
            get {
                return ResourceManager.GetString("ClickOnCloudServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;b&gt;NEW&lt;/b&gt;..
        /// </summary>
        public static string ClickOnNewCloudService {
            get {
                return ResourceManager.GetString("ClickOnNewCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the Open Data Platform Installer to function properly, an &lt;b&gt;empty Cloud Service&lt;/b&gt; is required under your Windows Azure subscription to install selected products..
        /// </summary>
        public static string ForOpenDataPlatformInstallerToFunction {
            get {
                return ResourceManager.GetString("ForOpenDataPlatformInstallerToFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to &lt;a href=&quot;https://manage.windowsazure.com&quot; target=&quot;_blank&quot;&gt;https://manage.windowsazure.com&lt;/a&gt; and sign in..
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to create a Windows Azure Cloud Service.
        /// </summary>
        public static string HowToCreateAWindowsAzureCloudService {
            get {
                return ResourceManager.GetString("HowToCreateAWindowsAzureCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the panel that appears, choose &lt;b&gt;QUICK CREATE&lt;/b&gt;. Then enter your URL and select a region..
        /// </summary>
        public static string InTheCreateANewCloudService {
            get {
                return ResourceManager.GetString("InTheCreateANewCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following steps allow you to create a &lt;b&gt;Cloud Service&lt;/b&gt; under your Windows Azure subscription. Go ahead and create a hosted service for every product you wish to install..
        /// </summary>
        public static string TheFollowingStepsAllowYou {
            get {
                return ResourceManager.GetString("TheFollowingStepsAllowYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must create one &lt;b&gt;Cloud Service&lt;/b&gt; for every product you install and cannot deploy multiple products to one Cloud Service. In the deployment step of the installer, you will have to select which &lt;b&gt;Cloud Service&lt;/b&gt; the product should be assigned to..
        /// </summary>
        public static string YouMustCreateOneCloudService {
            get {
                return ResourceManager.GetString("YouMustCreateOneCloudService", resourceCulture);
            }
        }
    }
}
