//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18051
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateSqlAzureDbResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateSqlAzureDbResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.Help.CreateSqlAzureDbResource", typeof(CreateSqlAzureDbResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check &lt;b&gt;Allow other Windows Azure services to access this server &lt;/b&gt;and specify
        ///                any other IP ranges to allow to access the SQL Server.
        /// </summary>
        public static string CheckAllowOtherWindowsAzure {
            get {
                return ResourceManager.GetString("CheckAllowOtherWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click &lt;b&gt;Finish&lt;/b&gt;. At this point the database and server will be created in a
        ///                few minutes..
        /// </summary>
        public static string ClickFinish {
            get {
                return ResourceManager.GetString("ClickFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on &lt;b&gt;Database&lt;/b&gt;.
        /// </summary>
        public static string ClickOnDatabase {
            get {
                return ResourceManager.GetString("ClickOnDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on the &lt;b&gt;Subscriptions &lt;/b&gt;folder.
        /// </summary>
        public static string ClickOnTheSubscriptionFolder {
            get {
                return ResourceManager.GetString("ClickOnTheSubscriptionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click the &lt;b&gt;Create a New Database &lt;/b&gt;button.
        /// </summary>
        public static string ClickTheCreateANewDatabase {
            get {
                return ResourceManager.GetString("ClickTheCreateANewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create an administrator login and password and click &lt;b&gt;Next&lt;/b&gt;. &lt;b&gt;NOTE: &lt;/b&gt;write
        ///                these down somewhere as you will need them for later..
        /// </summary>
        public static string CreateAnAdministratorLogin {
            get {
                return ResourceManager.GetString("CreateAnAdministratorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a &lt;b&gt;database name &lt;/b&gt;for your&lt;b&gt; &lt;/b&gt;database and select the edition and
        ///                maximum size. &lt;b&gt;NOTE: &lt;/b&gt;make a note of the database name as you will need it
        ///                for later.
        /// </summary>
        public static string EnterADatabaseName {
            get {
                return ResourceManager.GetString("EnterADatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to &lt;a href=&quot;https://manage.windowsazure.com&quot; target=&quot;_blank&quot;&gt;https://manage.windowsazure.com&lt;/a&gt; and sign in..
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How To Get Create SQL Azure Database.
        /// </summary>
        public static string HowToGetCreateSqlAzureDatabase {
            get {
                return ResourceManager.GetString("HowToGetCreateSqlAzureDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In the &lt;b&gt;Create Database &lt;/b&gt;dialog, select the subscription the create the database
        ///                on, and then select the database server and click &lt;b&gt;Next&lt;/b&gt;. Note, you can select
        ///                an existing database server or create a new one.
        /// </summary>
        public static string InTheCreateDatabaseDialog {
            get {
                return ResourceManager.GetString("InTheCreateDatabaseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the &lt;b&gt;Region&lt;/b&gt; to create the database in and click &lt;b&gt;Next&lt;/b&gt;.
        /// </summary>
        public static string SelectTheRegionToCreate {
            get {
                return ResourceManager.GetString("SelectTheRegionToCreate", resourceCulture);
            }
        }
    }
}
