//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18051
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateSqlAzureDbResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateSqlAzureDbResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.Help.CreateSqlAzureDbResource", typeof(CreateSqlAzureDbResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click &lt;b&gt;OK&lt;/b&gt;. At this point the database and server will be created in a few minutes..
        /// </summary>
        public static string ClickFinish {
            get {
                return ResourceManager.GetString("ClickFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on &lt;b&gt;SQL DATABASES&lt;/b&gt;..
        /// </summary>
        public static string ClickOnDatabase {
            get {
                return ResourceManager.GetString("ClickOnDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on &lt;b&gt;CREATE A SQL DATABASE&lt;/b&gt;..
        /// </summary>
        public static string ClickTheCreateANewDatabase {
            get {
                return ResourceManager.GetString("ClickTheCreateANewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create an administrator login and password. Select a region and do not forget to check the box &lt;b&gt;ALLOW WINDOWS AZURE SERVICES TO ACCESS THE SERVER&lt;/b&gt;..
        /// </summary>
        public static string CreateAnAdministratorLogin {
            get {
                return ResourceManager.GetString("CreateAnAdministratorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to &lt;a href=&quot;https://manage.windowsazure.com&quot; target=&quot;_blank&quot;&gt;https://manage.windowsazure.com&lt;/a&gt; and sign in..
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How to create a SQL Azure Database.
        /// </summary>
        public static string HowToGetCreateSqlAzureDatabase {
            get {
                return ResourceManager.GetString("HowToGetCreateSqlAzureDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In the &lt;b&gt;NEW SQL DATABASE&lt;/b&gt; dialog, choose a name for your database. You can then select an existing database server or create a new one..
        /// </summary>
        public static string InTheCreateDatabaseDialog {
            get {
                return ResourceManager.GetString("InTheCreateDatabaseDialog", resourceCulture);
            }
        }
    }
}
