//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GetDbUsernameResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetDbUsernameResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.Help.GetDbUsernameResource", typeof(GetDbUsernameResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;b&gt;SQL DATABASES&lt;/b&gt;..
        /// </summary>
        public static string ClickOnDatabase {
            get {
                return ResourceManager.GetString("ClickOnDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &lt;b&gt;DASHBOARD&lt;/b&gt; tab..
        /// </summary>
        public static string ClickOnTheDashboardTab {
            get {
                return ResourceManager.GetString("ClickOnTheDashboardTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &lt;b&gt;SERVERS&lt;/b&gt; tab..
        /// </summary>
        public static string ClickOnTheServersTab {
            get {
                return ResourceManager.GetString("ClickOnTheServersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &lt;b&gt;SQL Database&lt;/b&gt; server of your choice..
        /// </summary>
        public static string ClickOnYourServer {
            get {
                return ResourceManager.GetString("ClickOnYourServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the right side, you&apos;ll find the name of your &lt;b&gt;SQL Database&lt;/b&gt; server and the username of the administrator. You must fill the &lt;b&gt;Username&lt;/b&gt; field like this: &lt;i&gt;username@servername&lt;/i&gt;.
        /// </summary>
        public static string CopyUsername {
            get {
                return ResourceManager.GetString("CopyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to &lt;a href=&quot;https://manage.windowsazure.com&quot; target=&quot;_blank&quot;&gt;https://manage.windowsazure.com&lt;/a&gt; and sign in..
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to get the username of your SQL Azure Database.
        /// </summary>
        public static string HowToGetSqlAzureDatabaseUsername {
            get {
                return ResourceManager.GetString("HowToGetSqlAzureDatabaseUsername", resourceCulture);
            }
        }
    }
}
