//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GetSubscriptionIdResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetSubscriptionIdResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.Help.GetSubscriptionIdResource", typeof(GetSubscriptionIdResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on hosted Services.
        /// </summary>
        public static string ClickOnHostedServices {
            get {
                return ResourceManager.GetString("ClickOnHostedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on your Subscription that are displayed in the center pane.
        /// </summary>
        public static string ClickOnYourSubscriptionThatAreDisplayed {
            get {
                return ResourceManager.GetString("ClickOnYourSubscriptionThatAreDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to &lt;a href=&quot;http://windows.azure.com&quot; target=&quot;_blank&quot;&gt;http://windows.azure.com&lt;/a&gt; and sign in.
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Highlight the Subscription ID number, right click and on the popup menu click
        ///                &lt;b&gt;Copy&lt;/b&gt;.
        /// </summary>
        public static string HighlightTheSubscriptionIDNumber {
            get {
                return ResourceManager.GetString("HighlightTheSubscriptionIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How To Get Azure Subscription ID.
        /// </summary>
        public static string HowToGetAzureSubscriptionId {
            get {
                return ResourceManager.GetString("HowToGetAzureSubscriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In the properties Window you will find your &lt;b&gt;Subscription ID&lt;/b&gt; near the
        ///                bottom.
        /// </summary>
        public static string InThePropertiesWindow {
            get {
                return ResourceManager.GetString("InThePropertiesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste this value back in the &lt;b&gt;Azure Config &lt;/b&gt;page &lt;b&gt;Subscription Id
        ///                &lt;/b&gt;field.
        /// </summary>
        public static string PasteThisValueBack {
            get {
                return ResourceManager.GetString("PasteThisValueBack", resourceCulture);
            }
        }
    }
}
