//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18051
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GetTableStorageKeyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetTableStorageKeyResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.Help.GetTableStorageKeyResource", typeof(GetTableStorageKeyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click &lt;strong&gt;Close&lt;/strong&gt;..
        /// </summary>
        public static string ClickClose {
            get {
                return ResourceManager.GetString("ClickClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on &lt;b&gt;Storage Accounts&lt;/b&gt;.
        /// </summary>
        public static string ClickOnStorageAccounts {
            get {
                return ResourceManager.GetString("ClickOnStorageAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on the newly created Table Storage account (or existing account if a new one
        ///                is not created).
        /// </summary>
        public static string ClickOnTheNewlyCreatedStorage {
            get {
                return ResourceManager.GetString("ClickOnTheNewlyCreatedStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to &lt;a href=&quot;https://manage.windowsazure.com&quot; target=&quot;_blank&quot;&gt;https://manage.windowsazure.com&lt;/a&gt; and sign in..
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How to get the Azure Storage Account key.
        /// </summary>
        public static string HowToGetAzureTableStorageAccessKey {
            get {
                return ResourceManager.GetString("HowToGetAzureTableStorageAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In the Properties window find the &lt;b&gt;Primary Access Key &lt;/b&gt;header near the top
        ///                and click the &lt;b&gt;View &lt;/b&gt;button.
        /// </summary>
        public static string InThePropertiesWindowsFind {
            get {
                return ResourceManager.GetString("InThePropertiesWindowsFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In the &lt;b&gt;View Storage Access Keys&lt;/b&gt; popup window, click the copy icon. (Note
        ///                you may get a popup asking permission to copy to clipboard, click yes).
        /// </summary>
        public static string InTheViewStorageAccessKeys {
            get {
                return ResourceManager.GetString("InTheViewStorageAccessKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste this value back in the &lt;b&gt;Azure Config &lt;/b&gt;page &lt;b&gt;Primary Access Key &lt;/b&gt;
        ///                field.
        /// </summary>
        public static string PasteThisValueBack {
            get {
                return ResourceManager.GetString("PasteThisValueBack", resourceCulture);
            }
        }
    }
}
