//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18051
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Screenshots {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Screenshots() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.Help.Screenshots", typeof(Screenshots).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image001.jpg.
        /// </summary>
        public static string Image1 {
            get {
                return ResourceManager.GetString("Image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image010.jpg.
        /// </summary>
        public static string Image10 {
            get {
                return ResourceManager.GetString("Image10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image011.jpg.
        /// </summary>
        public static string Image11 {
            get {
                return ResourceManager.GetString("Image11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image012.jpg.
        /// </summary>
        public static string Image12 {
            get {
                return ResourceManager.GetString("Image12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image013.jpg.
        /// </summary>
        public static string Image13 {
            get {
                return ResourceManager.GetString("Image13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image014.jpg.
        /// </summary>
        public static string Image14 {
            get {
                return ResourceManager.GetString("Image14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image015.jpg.
        /// </summary>
        public static string Image15 {
            get {
                return ResourceManager.GetString("Image15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image016.jpg.
        /// </summary>
        public static string Image16 {
            get {
                return ResourceManager.GetString("Image16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image017.jpg.
        /// </summary>
        public static string Image17 {
            get {
                return ResourceManager.GetString("Image17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image018.jpg.
        /// </summary>
        public static string Image18 {
            get {
                return ResourceManager.GetString("Image18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image019.jpg.
        /// </summary>
        public static string Image19 {
            get {
                return ResourceManager.GetString("Image19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image002.jpg.
        /// </summary>
        public static string Image2 {
            get {
                return ResourceManager.GetString("Image2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image020.jpg.
        /// </summary>
        public static string Image20 {
            get {
                return ResourceManager.GetString("Image20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image021.jpg.
        /// </summary>
        public static string Image21 {
            get {
                return ResourceManager.GetString("Image21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image022.jpg.
        /// </summary>
        public static string Image22 {
            get {
                return ResourceManager.GetString("Image22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image023.jpg.
        /// </summary>
        public static string Image23 {
            get {
                return ResourceManager.GetString("Image23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image024.jpg.
        /// </summary>
        public static string Image24 {
            get {
                return ResourceManager.GetString("Image24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image025.jpg.
        /// </summary>
        public static string Image25 {
            get {
                return ResourceManager.GetString("Image25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image026.jpg.
        /// </summary>
        public static string Image26 {
            get {
                return ResourceManager.GetString("Image26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image027.jpg.
        /// </summary>
        public static string Image27 {
            get {
                return ResourceManager.GetString("Image27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image003.jpg.
        /// </summary>
        public static string Image3 {
            get {
                return ResourceManager.GetString("Image3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image004.jpg.
        /// </summary>
        public static string Image4 {
            get {
                return ResourceManager.GetString("Image4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image005.jpg.
        /// </summary>
        public static string Image5 {
            get {
                return ResourceManager.GetString("Image5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image006.jpg.
        /// </summary>
        public static string Image6 {
            get {
                return ResourceManager.GetString("Image6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image007.jpg.
        /// </summary>
        public static string Image7 {
            get {
                return ResourceManager.GetString("Image7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image008.jpg.
        /// </summary>
        public static string Image8 {
            get {
                return ResourceManager.GetString("Image8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image009.jpg.
        /// </summary>
        public static string Image9 {
            get {
                return ResourceManager.GetString("Image9", resourceCulture);
            }
        }
    }
}
