//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Screenshots {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Screenshots() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.Help.Screenshots", typeof(Screenshots).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image001.jpg.
        /// </summary>
        public static string Image1 {
            get {
                return ResourceManager.GetString("Image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image010.jpg.
        /// </summary>
        public static string Image10 {
            get {
                return ResourceManager.GetString("Image10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image011.jpg.
        /// </summary>
        public static string Image11 {
            get {
                return ResourceManager.GetString("Image11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image012.jpg.
        /// </summary>
        public static string Image12 {
            get {
                return ResourceManager.GetString("Image12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image013.jpg.
        /// </summary>
        public static string Image13 {
            get {
                return ResourceManager.GetString("Image13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image014.jpg.
        /// </summary>
        public static string Image14 {
            get {
                return ResourceManager.GetString("Image14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image015.jpg.
        /// </summary>
        public static string Image15 {
            get {
                return ResourceManager.GetString("Image15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image016.jpg.
        /// </summary>
        public static string Image16 {
            get {
                return ResourceManager.GetString("Image16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image017.jpg.
        /// </summary>
        public static string Image17 {
            get {
                return ResourceManager.GetString("Image17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image018.jpg.
        /// </summary>
        public static string Image18 {
            get {
                return ResourceManager.GetString("Image18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image019.jpg.
        /// </summary>
        public static string Image19 {
            get {
                return ResourceManager.GetString("Image19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image002.jpg.
        /// </summary>
        public static string Image2 {
            get {
                return ResourceManager.GetString("Image2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image020.jpg.
        /// </summary>
        public static string Image20 {
            get {
                return ResourceManager.GetString("Image20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image021.jpg.
        /// </summary>
        public static string Image21 {
            get {
                return ResourceManager.GetString("Image21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image022.jpg.
        /// </summary>
        public static string Image22 {
            get {
                return ResourceManager.GetString("Image22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image023.jpg.
        /// </summary>
        public static string Image23 {
            get {
                return ResourceManager.GetString("Image23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image024.jpg.
        /// </summary>
        public static string Image24 {
            get {
                return ResourceManager.GetString("Image24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image025.jpg.
        /// </summary>
        public static string Image25 {
            get {
                return ResourceManager.GetString("Image25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image026.jpg.
        /// </summary>
        public static string Image26 {
            get {
                return ResourceManager.GetString("Image26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image027.jpg.
        /// </summary>
        public static string Image27 {
            get {
                return ResourceManager.GetString("Image27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image003.jpg.
        /// </summary>
        public static string Image3 {
            get {
                return ResourceManager.GetString("Image3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image004.jpg.
        /// </summary>
        public static string Image4 {
            get {
                return ResourceManager.GetString("Image4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image005.jpg.
        /// </summary>
        public static string Image5 {
            get {
                return ResourceManager.GetString("Image5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image006.jpg.
        /// </summary>
        public static string Image6 {
            get {
                return ResourceManager.GetString("Image6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image007.jpg.
        /// </summary>
        public static string Image7 {
            get {
                return ResourceManager.GetString("Image7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image008.jpg.
        /// </summary>
        public static string Image8 {
            get {
                return ResourceManager.GetString("Image8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image009.jpg.
        /// </summary>
        public static string Image9 {
            get {
                return ResourceManager.GetString("Image9", resourceCulture);
            }
        }
    }
}
