//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODI.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OdiAppRepoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OdiAppRepoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODI.Resources.Models.OdiAppRepoResource", typeof(OdiAppRepoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGDI DataLab.
        /// </summary>
        public static string DataLab {
            get {
                return ResourceManager.GetString("DataLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;To configure OGDI DataLab on Windows Azure, we will first need to get information on blob storage information plus other settings. 
        ///You will need to provide us with various items below so we can configure the package of installing OGDI DataLab on Windows Azure.&lt;/p&gt;.
        /// </summary>
        public static string DataLabConfigHelpText {
            get {
                return ResourceManager.GetString("DataLabConfigHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGDI DataLab is a solution that makes it possible for agencies to publish government and public data more quickly and efficiently..
        /// </summary>
        public static string DataLabDescription {
            get {
                return ResourceManager.GetString("DataLabDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Public.
        /// </summary>
        public static string DataPublic {
            get {
                return ResourceManager.GetString("DataPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;To configure Data Public on Windows Azure, we will first need to get information on a SQL Azure database to use. 
        ///You will need to provide us with various items below so we can configure the package for installing Data Public on Windows Azure.&lt;/p&gt;.
        /// </summary>
        public static string DataPublicConfigHelpText {
            get {
                return ResourceManager.GetString("DataPublicConfigHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataPublic: a web portal for Open Government initiatives..
        /// </summary>
        public static string DataPublicDescription {
            get {
                return ResourceManager.GetString("DataPublicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drupal.
        /// </summary>
        public static string Drupal {
            get {
                return ResourceManager.GetString("Drupal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;To configure Drupal on Windows Azure, we will first need to get information on a SQL Azure database to use. 
        ///You will need to provide us with various items below so we can configure the package of installing Drupal on Windows Azure.&lt;/p&gt;.
        /// </summary>
        public static string DrupalConfigHelpText {
            get {
                return ResourceManager.GetString("DrupalConfigHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drupal is an open source content management platform powering millions of websites and applications. It’s built, used, and supported by an active and diverse community of people around the world..
        /// </summary>
        public static string DrupalDescription {
            get {
                return ResourceManager.GetString("DrupalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenIntel.
        /// </summary>
        public static string OpenIntel {
            get {
                return ResourceManager.GetString("OpenIntel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;To configure OpenIntel on Windows Azure, we will first need to get information on a SQL Azure database to use and blob storage information. 
        ///You will need to provide us with various items below so we can configure the package of installing OpenIntel on Windows Azure.&lt;/p&gt;.
        /// </summary>
        public static string OpenIntelConfigHelpText {
            get {
                return ResourceManager.GetString("OpenIntelConfigHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Intel is an accelerator for governments and private companies to rapidly build open data portals and killer business intelligence solutions with an emphasis on spatial analysis, data interaction and visualization..
        /// </summary>
        public static string OpenIntelDescription {
            get {
                return ResourceManager.GetString("OpenIntelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODAF Openturf.
        /// </summary>
        public static string Openturf {
            get {
                return ResourceManager.GetString("Openturf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;To configure ODAF OpenTurf on Windows Azure, we will first need to get information on a SQL Azure database to use, set some application settings, Twitter settings and blob storage info.&lt;/p&gt;
        ///&lt;p&gt;You will need to provide us with various items below so we can configure the package of installing ODAF OpenTurf on Windows Azure.&lt;/p&gt;.
        /// </summary>
        public static string OpenturfConfigHelpText {
            get {
                return ResourceManager.GetString("OpenturfConfigHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an OpenData Framework that makes it easy to Add and Consume OpenData Endpoints into a reusable code base..
        /// </summary>
        public static string OpenturfDescription {
            get {
                return ResourceManager.GetString("OpenturfDescription", resourceCulture);
            }
        }
    }
}
