//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddCertificateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddCertificateResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODI.Resources.Views.Help.AddCertificateResource", typeof(AddCertificateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Ok.
        /// </summary>
        public static string ClickOk {
            get {
                return ResourceManager.GetString("ClickOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on Add Certificate.
        /// </summary>
        public static string ClickOnAddCertificate {
            get {
                return ResourceManager.GetString("ClickOnAddCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;strong&gt;Management Certificates&lt;/strong&gt;.
        /// </summary>
        public static string ClickOnManagementCertificates {
            get {
                return ResourceManager.GetString("ClickOnManagementCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the Browse button and select the generated certificate that was downloaded
        ///            to your computer..
        /// </summary>
        public static string ClickTheBrowserButtonAndSelect {
            get {
                return ResourceManager.GetString("ClickTheBrowserButtonAndSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the &lt;a href=&quot;http://windows.azure.com&quot; target=&quot;_blank&quot;&gt;Management Site&lt;/a&gt;
        ///            and sign in.
        /// </summary>
        public static string GoToManagementSite {
            get {
                return ResourceManager.GetString("GoToManagementSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Add a Certificate.
        /// </summary>
        public static string HowToAddACertificate {
            get {
                return ResourceManager.GetString("HowToAddACertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the Add New Management Certificate popup window select the subscription to add
        ///            to add the generated certificate..
        /// </summary>
        public static string InTheAddNewManagementCertificate {
            get {
                return ResourceManager.GetString("InTheAddNewManagementCertificate", resourceCulture);
            }
        }
    }
}
