//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateTableStorageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateTableStorageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODI.Resources.Views.Help.CreateTableStorageResource", typeof(CreateTableStorageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;b&gt;OK. &lt;/b&gt;At this point the Table Storage account will take a few
        ///                minutes to be created..
        /// </summary>
        public static string ClickOkAtThisPoint {
            get {
                return ResourceManager.GetString("ClickOkAtThisPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;b&gt;New Storage Account&lt;/b&gt;.
        /// </summary>
        public static string ClickOnNewStorageAccount {
            get {
                return ResourceManager.GetString("ClickOnNewStorageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;b&gt;Storage Accounts&lt;/b&gt;.
        /// </summary>
        public static string ClickOnStorageAccounts {
            get {
                return ResourceManager.GetString("ClickOnStorageAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to &lt;a href=&quot;http://windows.azure.com&quot; target=&quot;_blank&quot;&gt;http://windows.azure.com&lt;/a&gt; and sign in.
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Get Create Azure Storage.
        /// </summary>
        public static string HowToGetCreateAzureStorage {
            get {
                return ResourceManager.GetString("HowToGetCreateAzureStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the &lt;b&gt;Create a New Storage Account &lt;/b&gt;dialog, select your &lt;b&gt;Subscription,
        ///                &lt;/b&gt;enter a unique name for the &lt;b&gt;URL&lt;/b&gt;, choose the &lt;b&gt;Region or Affinity &lt;/b&gt;
        ///                group of choice.
        /// </summary>
        public static string InTheCreateANewStorageAccount {
            get {
                return ResourceManager.GetString("InTheCreateANewStorageAccount", resourceCulture);
            }
        }
    }
}
