//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateHostedServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateHostedServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODI.Resources.Views.Help.CreateHostedServiceResource", typeof(CreateHostedServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK and after about 10seconds your &lt;strong&gt;Hosted Service &lt;/strong&gt;will be
        ///                created..
        /// </summary>
        public static string ClickOkAndAfter {
            get {
                return ResourceManager.GetString("ClickOkAndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on hosted Services.
        /// </summary>
        public static string ClickOnHostedServices {
            get {
                return ResourceManager.GetString("ClickOnHostedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;strong&gt;New Hosted Service&lt;br&gt;.
        /// </summary>
        public static string ClickOnNewHostedService {
            get {
                return ResourceManager.GetString("ClickOnNewHostedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on your Subscription that are displayed in the center pane.
        /// </summary>
        public static string ClickOnYourSubscription {
            get {
                return ResourceManager.GetString("ClickOnYourSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the Open Data Platform Installer to function properly, an &lt;strong&gt;empty Hosted Service&lt;/strong&gt;
        ///        is required under your Windows Azure subscription to install selected products..
        /// </summary>
        public static string ForOpenDataPlatformInstallerToFunction {
            get {
                return ResourceManager.GetString("ForOpenDataPlatformInstallerToFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to &lt;a href=&quot;http://windows.azure.com&quot; target=&quot;_blank&quot;&gt;http://windows.azure.com&lt;/a&gt; and sign in.
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Create A Windows Azure Hosted Service.
        /// </summary>
        public static string HowToCreateAWindowsAzureHostedService {
            get {
                return ResourceManager.GetString("HowToCreateAWindowsAzureHostedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the &lt;strong&gt;Create a New Hosted Service&lt;/strong&gt; dialog box that pops up select
        ///                the &lt;strong&gt;Subscription&lt;/strong&gt;, a name for the service, prefix for the service
        ///                (the prefix can be the same as the name) and choose a region. For deployment options
        ///                check &lt;strong&gt;Do Not Deploy.&lt;/strong&gt;.
        /// </summary>
        public static string InTheCreateANewHostedService {
            get {
                return ResourceManager.GetString("InTheCreateANewHostedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following steps allow you to create a &lt;strong&gt;Hosted Service&lt;/strong&gt; under
        ///        your Windows Azure subscription. Go ahead and create a hosted service for every product you wish to install..
        /// </summary>
        public static string TheFollowingStepsAllowYou {
            get {
                return ResourceManager.GetString("TheFollowingStepsAllowYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must create one &lt;strong&gt;Hosted Service&lt;/strong&gt; for every product you install
        ///        and cannot deploy multiple products to one &lt;strong&gt;Hosted Service. &lt;/strong&gt;In the
        ///        deployment step of the installer, you will have the option to select which &lt;strong&gt;Hosted
        ///            Service&lt;/strong&gt; the product should be assigned to..
        /// </summary>
        public static string YouMustCreateOneHostedService {
            get {
                return ResourceManager.GetString("YouMustCreateOneHostedService", resourceCulture);
            }
        }
    }
}
