//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateSqlAzureDbResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateSqlAzureDbResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODI.Resources.Views.Help.CreateSqlAzureDbResource", typeof(CreateSqlAzureDbResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &lt;b&gt;Allow other Windows Azure services to access this server &lt;/b&gt;and specify
        ///                any other IP ranges to allow to access the SQL Server.
        /// </summary>
        public static string CheckAllowOtherWindowsAzure {
            get {
                return ResourceManager.GetString("CheckAllowOtherWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;b&gt;Finish&lt;/b&gt;. At this point the database and server will be created in a
        ///                few minutes..
        /// </summary>
        public static string ClickFinish {
            get {
                return ResourceManager.GetString("ClickFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;b&gt;Database&lt;/b&gt;.
        /// </summary>
        public static string ClickOnDatabase {
            get {
                return ResourceManager.GetString("ClickOnDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &lt;b&gt;Subscriptions &lt;/b&gt;folder.
        /// </summary>
        public static string ClickOnTheSubscriptionFolder {
            get {
                return ResourceManager.GetString("ClickOnTheSubscriptionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the &lt;b&gt;Create a New Database &lt;/b&gt;button.
        /// </summary>
        public static string ClickTheCreateANewDatabase {
            get {
                return ResourceManager.GetString("ClickTheCreateANewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an administrator login and password and click &lt;b&gt;Next&lt;/b&gt;. &lt;b&gt;NOTE: &lt;/b&gt;write
        ///                these down somewhere as you will need them for later..
        /// </summary>
        public static string CreateAnAdministratorLogin {
            get {
                return ResourceManager.GetString("CreateAnAdministratorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a &lt;b&gt;database name &lt;/b&gt;for your&lt;b&gt; &lt;/b&gt;database and select the edition and
        ///                maximum size. &lt;b&gt;NOTE: &lt;/b&gt;make a note of the database name as you will need it
        ///                for later.
        /// </summary>
        public static string EnterADatabaseName {
            get {
                return ResourceManager.GetString("EnterADatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to &lt;a href=&quot;http://windows.azure.com&quot; target=&quot;_blank&quot;&gt;http://windows.azure.com&lt;/a&gt; and sign in.
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Get Create SQL Azure Database.
        /// </summary>
        public static string HowToGetCreateSqlAzureDatabase {
            get {
                return ResourceManager.GetString("HowToGetCreateSqlAzureDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the &lt;b&gt;Create Database &lt;/b&gt;dialog, select the subscription the create the database
        ///                on, and then select the database server and click &lt;b&gt;Next&lt;/b&gt;. Note, you can select
        ///                an existing database server or create a new one.
        /// </summary>
        public static string InTheCreateDatabaseDialog {
            get {
                return ResourceManager.GetString("InTheCreateDatabaseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the &lt;b&gt;Region&lt;/b&gt; to create the database in and click &lt;b&gt;Next&lt;/b&gt;.
        /// </summary>
        public static string SelectTheRegionToCreate {
            get {
                return ResourceManager.GetString("SelectTheRegionToCreate", resourceCulture);
            }
        }
    }
}
