//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GetDbUsernameResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetDbUsernameResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODI.Resources.Views.Help.GetDbUsernameResource", typeof(GetDbUsernameResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &lt;b&gt;Database&lt;/b&gt;.
        /// </summary>
        public static string ClickOnDatabase {
            get {
                return ResourceManager.GetString("ClickOnDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &lt;b&gt;Subscriptions &lt;/b&gt;folder.
        /// </summary>
        public static string ClickOnTheSubscriptionsFoler {
            get {
                return ResourceManager.GetString("ClickOnTheSubscriptionsFoler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &lt;strong&gt;Subscription&lt;/strong&gt; your database resides in and expand the
        ///                selection&lt;/b&gt;.
        /// </summary>
        public static string ClickOnTheSubscriptionYourDatabase {
            get {
                return ResourceManager.GetString("ClickOnTheSubscriptionYourDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand the server and select your database.
        /// </summary>
        public static string ExpandTheServerAndSelectYouDatabase {
            get {
                return ResourceManager.GetString("ExpandTheServerAndSelectYouDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to &lt;a href=&quot;http://windows.azure.com&quot; target=&quot;_blank&quot;&gt;http://windows.azure.com&lt;/a&gt; and sign in.
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight this value, right click and then click copy..
        /// </summary>
        public static string HighlightThisValue {
            get {
                return ResourceManager.GetString("HighlightThisValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Get SQL Azure Database Username.
        /// </summary>
        public static string HowToGetSqlAzureDatabaseUsername {
            get {
                return ResourceManager.GetString("HowToGetSqlAzureDatabaseUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the properties Window look for the &lt;strong&gt;Administrator Login&lt;/strong&gt;.
        /// </summary>
        public static string InThePropertiesWindow {
            get {
                return ResourceManager.GetString("InThePropertiesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste this value back into the &lt;strong&gt;Username&lt;/strong&gt; field. &lt;strong&gt;NOTE:&lt;/strong&gt; the username must be in the format of &lt;strong&gt;username@servername&lt;/strong&gt;.
        /// </summary>
        public static string PasteThisValueBackIntoTheUsername {
            get {
                return ResourceManager.GetString("PasteThisValueBackIntoTheUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your server.
        /// </summary>
        public static string SelectYourServer {
            get {
                return ResourceManager.GetString("SelectYourServer", resourceCulture);
            }
        }
    }
}
