//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODI.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GetSubscriptionIdResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetSubscriptionIdResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODI.Resources.Views.Help.GetSubscriptionIdResource", typeof(GetSubscriptionIdResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on hosted Services.
        /// </summary>
        public static string ClickOnHostedServices {
            get {
                return ResourceManager.GetString("ClickOnHostedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on your Subscription that are displayed in the center pane.
        /// </summary>
        public static string ClickOnYourSubscriptionThatAreDisplayed {
            get {
                return ResourceManager.GetString("ClickOnYourSubscriptionThatAreDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to &lt;a href=&quot;http://windows.azure.com&quot; target=&quot;_blank&quot;&gt;http://windows.azure.com&lt;/a&gt; and sign in.
        /// </summary>
        public static string GoToWindowsAzure {
            get {
                return ResourceManager.GetString("GoToWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the Subscription ID number, right click and on the popup menu click
        ///                &lt;b&gt;Copy&lt;/b&gt;.
        /// </summary>
        public static string HighlightTheSubscriptionIDNumber {
            get {
                return ResourceManager.GetString("HighlightTheSubscriptionIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Get Azure Subscription ID.
        /// </summary>
        public static string HowToGetAzureSubscriptionId {
            get {
                return ResourceManager.GetString("HowToGetAzureSubscriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the properties Window you will find your &lt;b&gt;Subscription ID&lt;/b&gt; near the
        ///                bottom.
        /// </summary>
        public static string InThePropertiesWindow {
            get {
                return ResourceManager.GetString("InThePropertiesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste this value back in the &lt;b&gt;Azure Config &lt;/b&gt;page &lt;b&gt;Subscription Id
        ///                &lt;/b&gt;field.
        /// </summary>
        public static string PasteThisValueBack {
            get {
                return ResourceManager.GetString("PasteThisValueBack", resourceCulture);
            }
        }
    }
}
