//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Views.Tpl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TasklistResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TasklistResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Views.Tpl.TasklistResource", typeof(TasklistResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before You Start.
        /// </summary>
        public static string BeforeYouStart {
            get {
                return ResourceManager.GetString("BeforeYouStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you start the process of installing any of the products included with Open Data Platform Installer there are a few pre-requisites required before using the tool. &lt;a id=&quot;showMore&quot; href=&quot;&quot;&gt;Show more&lt;/a&gt;.
        /// </summary>
        public static string BeforeYouStartTheProcess {
            get {
                return ResourceManager.GetString("BeforeYouStartTheProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Components.
        /// </summary>
        public static string ConfigureComponents {
            get {
                return ResourceManager.GetString("ConfigureComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize install procedure.
        /// </summary>
        public static string FinalizeInstallProcedure {
            get {
                return ResourceManager.GetString("FinalizeInstallProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Service.
        /// </summary>
        public static string HostedService {
            get {
                return ResourceManager.GetString("HostedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don’t already have a Windows Azure account you can create one at &lt;a href=&quot;http://www.windowsazure.com&quot; target=&quot;_blank&quot;&gt;www.windowsazure.com&lt;/a&gt;. Here you will find all appropriate information and steps required to create an account..
        /// </summary>
        public static string IfYouDontAlreadyHaveAWindowsAzure {
            get {
                return ResourceManager.GetString("IfYouDontAlreadyHaveAWindowsAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Certificates.
        /// </summary>
        public static string ManagementCertificates {
            get {
                return ResourceManager.GetString("ManagementCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once your account is created you will need to create a Cloud Service under your Windows Azure subscription to deploy the products to. This Cloud Service must be empty or we cannot deploy to it using the Open Data Platform Installer..
        /// </summary>
        public static string OnceYourAccountIsCreated {
            get {
                return ResourceManager.GetString("OnceYourAccountIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Data Platform Installer for Windows Azure.
        /// </summary>
        public static string OpenDataPlatformInstalled {
            get {
                return ResourceManager.GetString("OpenDataPlatformInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select components to install.
        /// </summary>
        public static string SelectComponentsToInstall {
            get {
                return ResourceManager.GetString("SelectComponentsToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Account.
        /// </summary>
        public static string StorageAccount {
            get {
                return ResourceManager.GetString("StorageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Open Data Platform Installer (ODPI) will allow even non-technical folks to get a customized collection of Open Data applications up and running on Windows Azure by filling out a few details..
        /// </summary>
        public static string TheOpenDataPlatformInstallerODPI {
            get {
                return ResourceManager.GetString("TheOpenDataPlatformInstallerODPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Open Data Platform Installer requires the use of a Storage Account to temporarily store packages while deploying. These packages will be deleted, but the Storage Account will remain in place. We&apos;ll let you know when you need these details but if you want to create one now click &lt;a href=&quot;#&quot; data-toggle=&quot;modal&quot; data-target=&quot;#createTableStorage&quot;&gt;here&lt;/a&gt; for details on how to create one..
        /// </summary>
        public static string TheOpenDataPlatformInstallerRequires {
            get {
                return ResourceManager.GetString("TheOpenDataPlatformInstallerRequires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To allow the Open Data Platform Installer access to your Windows Azure account, you will be required to add temporary certificates to your Windows Azure account. Don’t worry, we automatically create the certificates, we’ll show you how to add the certificates to your Azure account when the time is right..
        /// </summary>
        public static string ToAllowOpenDataPlatformInstaller {
            get {
                return ResourceManager.GetString("ToAllowOpenDataPlatformInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Azure Account.
        /// </summary>
        public static string WindowsAzureAccount {
            get {
                return ResourceManager.GetString("WindowsAzureAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must also create a separate Cloud Service for every product you install. Please see, &lt;a href=&quot;#&quot; data-toggle=&quot;modal&quot; data-target=&quot;#CreateCloudService&quot; rel=&quot;tooltip&quot; data-original-title=&quot;Click to see how&quot;&gt;how to create a Cloud Service&lt;/a&gt;..
        /// </summary>
        public static string YouMustAlsoCreate {
            get {
                return ResourceManager.GetString("YouMustAlsoCreate", resourceCulture);
            }
        }
    }
}
