//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPI.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OdpiAppRepoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OdpiAppRepoResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODPI.Resources.Models.OdpiAppRepoResource", typeof(OdpiAppRepoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Data Citizen Portal.
        /// </summary>
        public static string CitizenPortalOpenData {
            get {
                return ResourceManager.GetString("CitizenPortalOpenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;p&gt;To configure the Open Data Citizen Portal on Windows Azure, you will need to provide us with various items below so we can configure the package of installing the Open Data Citizen Portal on Windows Azure&lt;/p&gt;.
        /// </summary>
        public static string CitizenPortalOpenDataConfigHelpText {
            get {
                return ResourceManager.GetString("CitizenPortalOpenDataConfigHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Open Data Citizen Portal is a web site particularly adapted to the public and offering a user friendly interface..
        /// </summary>
        public static string CitizenPortalOpenDataDescription {
            get {
                return ResourceManager.GetString("CitizenPortalOpenDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OGDI DataLab.
        /// </summary>
        public static string DataLab {
            get {
                return ResourceManager.GetString("DataLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;p&gt;To configure OGDI DataLab on Windows Azure, we will first need to get information on blob storage information plus other settings. 
        ///You will need to provide us with various items below so we can configure the package of installing OGDI DataLab on Windows Azure.&lt;/p&gt;.
        /// </summary>
        public static string DataLabConfigHelpText {
            get {
                return ResourceManager.GetString("DataLabConfigHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OGDI DataLab is a solution that makes it possible for agencies to publish government and public data more quickly and efficiently..
        /// </summary>
        public static string DataLabDescription {
            get {
                return ResourceManager.GetString("DataLabDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data Public.
        /// </summary>
        public static string DataPublic {
            get {
                return ResourceManager.GetString("DataPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;p&gt;To configure Data Public on Windows Azure, we will first need to get information on a SQL Azure database to use. 
        ///You will need to provide us with various items below so we can configure the package for installing Data Public on Windows Azure.&lt;/p&gt;.
        /// </summary>
        public static string DataPublicConfigHelpText {
            get {
                return ResourceManager.GetString("DataPublicConfigHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DataPublic: a web portal for Open Government initiatives..
        /// </summary>
        public static string DataPublicDescription {
            get {
                return ResourceManager.GetString("DataPublicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drupal.
        /// </summary>
        public static string Drupal {
            get {
                return ResourceManager.GetString("Drupal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;p&gt;To configure Drupal on Windows Azure, we will first need to get information on a SQL Azure database to use. 
        ///You will need to provide us with various items below so we can configure the package of installing Drupal on Windows Azure.&lt;/p&gt;.
        /// </summary>
        public static string DrupalConfigHelpText {
            get {
                return ResourceManager.GetString("DrupalConfigHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drupal is an open source content management platform powering millions of websites and applications. It’s built, used, and supported by an active and diverse community of people around the world..
        /// </summary>
        public static string DrupalDescription {
            get {
                return ResourceManager.GetString("DrupalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OpenIntel.
        /// </summary>
        public static string OpenIntel {
            get {
                return ResourceManager.GetString("OpenIntel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;p&gt;To configure OpenIntel on Windows Azure, we will first need to get information on a SQL Azure database to use and blob storage information. 
        ///You will need to provide us with various items below so we can configure the package of installing OpenIntel on Windows Azure.&lt;/p&gt;.
        /// </summary>
        public static string OpenIntelConfigHelpText {
            get {
                return ResourceManager.GetString("OpenIntelConfigHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Intel is an accelerator for governments and private companies to rapidly build open data portals and killer business intelligence solutions with an emphasis on spatial analysis, data interaction and visualization..
        /// </summary>
        public static string OpenIntelDescription {
            get {
                return ResourceManager.GetString("OpenIntelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ODAF Openturf.
        /// </summary>
        public static string Openturf {
            get {
                return ResourceManager.GetString("Openturf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;p&gt;To configure ODAF OpenTurf on Windows Azure, we will first need to get information on a SQL Azure database to use, set some application settings, Twitter settings and blob storage info.&lt;/p&gt;
        ///&lt;p&gt;You will need to provide us with various items below so we can configure the package of installing ODAF OpenTurf on Windows Azure.&lt;/p&gt;.
        /// </summary>
        public static string OpenturfConfigHelpText {
            get {
                return ResourceManager.GetString("OpenturfConfigHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is an OpenData Framework that makes it easy to Add and Consume OpenData Endpoints into a reusable code base..
        /// </summary>
        public static string OpenturfDescription {
            get {
                return ResourceManager.GetString("OpenturfDescription", resourceCulture);
            }
        }
    }
}
