//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODI.Resources.Views.ConfTpl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataLabResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataLabResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODI.Resources.Views.ConfTpl.DataLabResource", typeof(DataLabResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings will allow DataLab to be customized when installed on Azure.
        ///        You will need to provide the following.
        /// </summary>
        public static string ApplicationSettingsWillAllowDataLab {
            get {
                return ResourceManager.GetString("ApplicationSettingsWillAllowDataLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob Storage Info.
        /// </summary>
        public static string BlobStorageInfo {
            get {
                return ResourceManager.GetString("BlobStorageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Catalog definition.
        /// </summary>
        public static string CatalogDefinition {
            get {
                return ResourceManager.GetString("CatalogDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section allows you to configure the data catalog that OGDI DataLab will use. Leave this section blank if you want to use an extern data service..
        /// </summary>
        public static string CatalogDefinitionDescription {
            get {
                return ResourceManager.GetString("CatalogDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see how.
        /// </summary>
        public static string ClickToSeeHow {
            get {
                return ResourceManager.GetString("ClickToSeeHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Service DNS.
        /// </summary>
        public static string DataServiceDNS {
            get {
                return ResourceManager.GetString("DataServiceDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once complete you will need to provide the following:.
        /// </summary>
        public static string OnceComplete {
            get {
                return ResourceManager.GetString("OnceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Access Key.
        /// </summary>
        public static string PrimaryAccessKey {
            get {
                return ResourceManager.GetString("PrimaryAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha Private Key.
        /// </summary>
        public static string RecaptchaPrivateKey {
            get {
                return ResourceManager.GetString("RecaptchaPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha Public Key.
        /// </summary>
        public static string RecaptchaPublickey {
            get {
                return ResourceManager.GetString("RecaptchaPublickey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Account Name.
        /// </summary>
        public static string StorageAccountName {
            get {
                return ResourceManager.GetString("StorageAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The use of Blob Storage is required for this package. If you already have an existing
        ///        Storage Account.
        ///    If you need to create a storage account for blob storage, click &lt;a href=&quot;#&quot; data-toggle=&quot;modal&quot;
        ///        data-target=&quot;#createTableStorage&quot;&gt;here&lt;/a&gt; for details on how to create one..
        /// </summary>
        public static string TheUseOfBlobStorageIsRequired {
            get {
                return ResourceManager.GetString("TheUseOfBlobStorageIsRequired", resourceCulture);
            }
        }
    }
}
