//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODI.Resources.Views.ConfTpl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlAzureResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlAzureResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODI.Resources.Views.ConfTpl.SqlAzureResource", typeof(SqlAzureResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see how.
        /// </summary>
        public static string ClickToSeeHow {
            get {
                return ResourceManager.GetString("ClickToSeeHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Hostname.
        /// </summary>
        public static string DatabaseHostname {
            get {
                return ResourceManager.GetString("DatabaseHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database-name.
        /// </summary>
        public static string DatabaseNamePlaceholder {
            get {
                return ResourceManager.GetString("DatabaseNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not have a SQL Azure database already created, click &lt;a href=&apos;#&apos; data-toggle=&apos;modal&apos;
        ///            data-target=&apos;#CreateSqlAzureDb&apos; rel=&apos;tooltip&apos; data-original-title=&apos;Click to see how&apos;&gt;
        ///            here&lt;/a&gt; for instructions to create a SQL Azure database..
        /// </summary>
        public static string IfYouDoNotHaveASqlAzure {
            get {
                return ResourceManager.GetString("IfYouDoNotHaveASqlAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the database is created, enter the values below..
        /// </summary>
        public static string OnceTheDataBaseIsCreated {
            get {
                return ResourceManager.GetString("OnceTheDataBaseIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password you created.
        /// </summary>
        public static string PasswordYouCreated {
            get {
                return ResourceManager.GetString("PasswordYouCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Azure Info.
        /// </summary>
        public static string SQLAzureInfo {
            get {
                return ResourceManager.GetString("SQLAzureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username@yourserver.
        /// </summary>
        public static string UsernameAtYourServer {
            get {
                return ResourceManager.GetString("UsernameAtYourServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yourserver.database.windows.com.
        /// </summary>
        public static string YourServerDatabase {
            get {
                return ResourceManager.GetString("YourServerDatabase", resourceCulture);
            }
        }
    }
}
